config/routes.rb
HYSMurhamaster::Application.routes.draw do

  root to: 'tournaments#index'

  resources :teams do
    resources :players
  end

  resources :calendars

  resources :tournaments do
    resources :ilmos
    resources :players
    resources :referees
    resources :teams, controller: 'tournaments/teams'
    resources :team_assignments
    resources :targets
    resources :rings do
      resources :assignments
    end
    resources :warrants
    resources :events
  end

  resources :special_tournaments do
    resources :ilmos, controller: 'special_tournaments/ilmos'
    resources :targets, controller: 'special_tournaments/targets'
    resources :players, controller: 'special_tournaments/players'
  end

  resources :referees do
    resources :players
  end

  resources :users do
    resources :targets
    resource :calendar
    resource :picture
  end

  get '/tournaments/:tournament_id/registration', to: 'ilmos#new', as: :tournament_registration
  match '/tournaments/:tournament_id/targets/:id/print' => 'targets#print'
  match '/tournaments/:tournament_id/resend_registration_mails' => 'ilmos#resend_registration_mails'
  match '/users/:id/reset_password' => 'users#reset_password'
  # match '/images/*file_name' => 'pictures#display'
  match 'pictures/:id/:style.:format', controller: 'pictures', action: 'display', conditions: { method: :get }
  resource :session
  match '/login' => 'users#index', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  # FIXME dirty hack for ropecon
  match '/ropecon', controller: 'special_tournaments/targets', action: 'index', defaults: {special_tournament_id: Tournament.all.select(&:special_event?).last.id }
end

app/controllers/special_tournaments/targets_controller.rb
class SpecialTournaments::TargetsController < ApplicationController
  skip_filter :is_authenticated?
  before_filter :is_special_tournament?
  before_filter :tournament_running?

  def index
    @targets = Tournament.find(params[:special_tournament_id]).players.active_players
  end

  def show
    @target = Player.find_by_tournament_id_and_id(params[:special_tournament_id], params[:id])
  end

  def is_special_tournament?
    return true if Tournament.find(params[:special_tournament_id]).special_event?
    redirect_to(root_path)
  end

  def tournament_running?
    return true if Tournament.find(params[:special_tournament_id]).is_running?
    redirect_to(root_path)
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController

  before_filter :is_hunter_or_referee?, :except => [:edit, :update]
  before_filter :is_target_tournament_referee?, :only => [:edit, :update]

  def show
    @target = Player.find(params[:id])
    @user = @target.user
    @tournament = @target.tournament

    @referee = false
    current_user.referees.each do |referee|
      if referee.tournament == @tournament
        @referee = true
      end
    end

    current_player = current_user.players.find(:first, :conditions => [ "tournament_id = ?", @tournament ])
    @detective = current_player.present? && current_player.detective?
  end

  def print
    @target = Player.find(params[:id])
    @user = @target.user
    render :print, :layout => false
  end

  def edit
    @target = Player.find(params[:id])
    @user = @target.user
    @tournament = @target.tournament
  end


  def update
    @tournament = Tournament.find(params[:tournament_id])
    @target = Player.find(params[:id])
    user = @target.user
    user.update_attributes(params[:user]) if params[:user]
    user.calendar.update_attributes(params[:calendar]) if params[:calendar]
    # not really DRY
    if params[:player]
      if params[:player][:photo]
        picture = Picture.new(params[:player])
        picture.user = user
        picture.save
      end
    end

    redirect_to tournament_target_path(@tournament, @target)

  end

  def is_target_tournament_referee?
    tournament = Tournament.find(params[:tournament_id])
    current_user.referees.each do |referee|
      if referee.tournament == tournament
        logger.info "current user is not referee for this tournament"
        return true
      end
    end
    redirect_to root_path
    return false
  end

  def is_hunter_or_referee?
    # check admin status
    if current_user.admin
      logger.info "current_user is admin"
      return true
    end

    target = Player.find(params[:id])

    # check referee status
    if current_user.is_referee_for?(target.tournament)
      return true
    end

    # check hunter status
    current_user.players.each do |player|
      logger.info "checking current_user's targets, player.id: #{player.id}"
      logger.info player.targets.inspect
      if player.targets.include? target
        logger.info "current_user has this target"
        return true
      end
    end
    logger.info "current_user not hunter nor referee/admin, redirecting"
    redirect_to root_path
    return false
  end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/edit.html.haml
%h2= @target.tournament.title
= link_to "Palaa pelaajan kohdesivulle", tournament_target_path(@target.tournament, @target)
%br/
= form_tag "users/#{@target.user.id}/reset_password" do
  = submit_tag "Resetoi käyttäjän salasana", :onclick => "return confirm('Haluatko varmasti resetoida käyttäjän salasanan?')"
- if @target.user.picture
  = image_tag(@target.user.picture.url)
- else
  %b PELAAJALLA EI KUVAA TOISTAISEKSI
= form_for([@tournament, @target], :html => { :multipart => true }, :url => tournament_target_path) do |f|
  %b Huom! Kuvien kokoraja on 16MB.
  %p
    = f.label "Uusi kuva: "
    %br/
    = f.file_field :photo
  %p
    = f.submit "Lähetä"
= form_for :user, :url => tournament_target_path(@tournament, @target), :html => { :method => :put } do |f|
  %table.top_align{:cellspacing => "20"}
    %tr
      %th
        %h3 Perustiedot
      %th
        %h3 Kalenteri
    %tr
      %td
        %p
          = f.label "Etunimi"
          %br/
          = f.text_field :first_name
        %p
          = f.label "Sukunimi"
          %br/
          = f.text_field :last_name
        %p.secret
          = f.label :Puhelin
          %br/
          = f.text_field :phone
        %p.secret
          = f.label "Sähköposti"
          %br/
          = f.text_field :email
        %p
          = f.label "Osoite"
          %br/
          = f.text_field :address
        %p
          = f.label "Oppilaitos"
          %br/
          = f.text_field :university
        %p
          = f.label "Tiedekunta/vast"
          %br/
          = f.text_field :faculty
        %p
          = f.label "Ainelaitos"
          %br/
          = f.text_field :department
        %p
          = f.label "Silmät"
          %br/
          = f.text_field :eyes
        %p
          = f.label "Silmälasit"
          %br/
          = f.select(:glasses, ["Aina", "Joskus", "Ei"])
        %p
          = f.label "Pituus"
          %br/
          = f.text_field :height, "size" => 3, "maxlength" => 3
          cm
        %p
          = f.label "Hiukset"
          %br/
          = f.text_field :hair
        %p
          = f.label "Muut tuntomerkit"
          %br/
          = f.text_field :other_notes
      %td
        - fields_for @user.calendar do |c|
          %p
            = c.label :Maanantai
            %br/
            = c.text_area :monday, "rows" => 5
          %p
            = c.label :Tiistai
            %br/
            = c.text_area :tuesday, "rows" => 5
          %p
            = c.label :Keskiviikko
            %br/
            = c.text_area :wednesday, "rows" => 5
          %p
            = c.label :Torstai
            %br/
            = c.text_area :thursday, "rows" => 5
          %p
            = c.label :Perjantai
            %br/
            = c.text_area :friday, "rows" => 5
          %p
            = c.label :Lauantai
            %br/
            = c.text_area :saturday, "rows" => 5
          %p
            = c.label :Sunnuntai
            %br/
            = c.text_area :sunday, "rows" => 5
          %p
            = c.label "Liikennevälineet, muut huomiot"
            %br/
            = c.text_area :misc, "rows" => 5
  %p
    = f.submit "Päivitä"

app/views/targets/print.html.haml
#main{:style => "display: inline-block;"}
  #image
    - if @target.user.picture
      = image_tag(@target.user.picture.url, :height => 640, :"margin-left" => 150)
    - else
      %b PELAAJALLA EI KUVAA TOISTAISEKSI
  %h2
    = @target.tournament.title
    \- #{@target.user.full_name} (#{@target.alias})
  #details
    #description{:style => "float:left;width:300"}
      %p
        %b Silmät:
        = h @user.eyes
      %p
        %b Silmälasit:
        = h @user.glasses
      %p
        %b Pituus:
        = h @user.height
      %p
        %b Hiukset:
        = h @user.hair
      %p
        %b Muut tuntomerkit:
        = h @user.other_notes
    #activity{:style => "float:right;width:300"}
      %p
        %b Ohjelma:
        = simple_format(@user.calendar.misc)
    %br{:style => "clear:both;"}/

app/views/targets/show.html.haml
%h2= @target.tournament.title
- if @referee
  = link_to 'Muokkaa pelaajan tietoja', edit_tournament_target_path(@target.tournament, @target)
%br/
- if @target.user.picture
  = image_tag(@target.user.picture.url)
- else
  %b PELAAJALLA EI KUVAA TOISTAISEKSI
%table.top_align{:cellspacing => '20'}
  %tr
    %th
      %h3 Perustiedot
      %h3
    %th
      %h3 Kalenteri
      %h3
  %tr
    %td
      - if current_user.is_referee_for?(@target.tournament)
        %i
          Kirjautunut viimeksi: #{nil_date_handler(@user.last_login)}
        %p
          %b Sähköposti:
          = h @user.email
        %p
          %b Puhelin:
          = h @user.phone
      - unless @referee
        - if @detective
          %p
            %b Peitenimi:
            = @target.alias
      %p
        %b Nimi:
        = h "#{@user.first_name} #{@user.last_name}"
      - if @target.team != nil
        %p
          %b Joukkue:
          = h @target.team.name
      %p
        %b Osoite:
        = h @user.address
      %p
        %b Oppilaitos:
        = h @user.university
        \/ #{h @user.faculty} /  #{h @user.department}
      %p
        %b Silmät:
        = h @user.eyes
      %p
        %b Silmälasit:
        = h @user.glasses
      %p
        %b Pituus:
        = h @user.height
      %p
        %b Hiukset:
        = h @user.hair
      %p
        %b Muut tuntomerkit:
        = h @user.other_notes
      - if @target.referee != nil
        %p
          %b Tuomari:
          = h @target.referee.user.full_name
          , #{h @target.referee.user.phone}
    %td
      - if @referee
        %i
          Päivitetty: #{finnish_date(@user.calendar.updated_at)}
      %p
        %b Maanantai:
        = simple_format(@user.calendar.monday)
      %p
        %b Tiistai:
        = simple_format(@user.calendar.tuesday)
      %p
        %b Keskiviikko:
        = simple_format(@user.calendar.wednesday)
      %p
        %b Torstai:
        = simple_format(@user.calendar.thursday)
      %p
        %b Perjantai:
        = simple_format(@user.calendar.friday)
      %p
        %b Lauantai:
        = simple_format(@user.calendar.saturday)
      %p
        %b Sunnuntai:
        = simple_format(@user.calendar.sunday)
      %p
        %b Liikennevälineet, muut huomiot:
        = simple_format(@user.calendar.misc)