config/routes.rb
HYSMurhamaster::Application.routes.draw do

  root to: 'tournaments#index'

  resources :teams do
    resources :players
  end

  resources :calendars

  resources :tournaments do
    resources :ilmos
    resources :players
    resources :referees
    resources :teams, controller: 'tournaments/teams'
    resources :team_assignments
    resources :targets
    resources :rings do
      resources :assignments
    end
    resources :warrants
    resources :events
  end

  resources :special_tournaments do
    resources :ilmos, controller: 'special_tournaments/ilmos'
    resources :targets, controller: 'special_tournaments/targets'
    resources :players, controller: 'special_tournaments/players'
  end

  resources :referees do
    resources :players
  end

  resources :users do
    resources :targets
    resource :calendar
    resource :picture
  end

  get '/tournaments/:tournament_id/registration', to: 'ilmos#new', as: :tournament_registration
  match '/tournaments/:tournament_id/targets/:id/print' => 'targets#print'
  match '/tournaments/:tournament_id/resend_registration_mails' => 'ilmos#resend_registration_mails'
  match '/users/:id/reset_password' => 'users#reset_password'
  # match '/images/*file_name' => 'pictures#display'
  match 'pictures/:id/:style.:format', controller: 'pictures', action: 'display', conditions: { method: :get }
  resource :session
  match '/login' => 'users#index', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  # FIXME dirty hack for ropecon
  match '/ropecon', controller: 'special_tournaments/targets', action: 'index', defaults: {special_tournament_id: Tournament.all.select(&:special_event?).last.id }
end

app/models/user.rb
class User < ActiveRecord::Base

  require 'digest/sha1'

  has_many :players
  has_one :calendar
  has_one :picture
  has_many :referees
  has_many :tournaments, :through => :referees

  accepts_nested_attributes_for :calendar
  accepts_nested_attributes_for :picture
  accepts_nested_attributes_for :players

  validates_presence_of :username, :password
  validates_uniqueness_of :username

  # validates_length_of :username, :in => 3..15

  # validates_length_of :password, :in => 5..30, :allow_blank => true, :on => :update
  # validates_length_of :password, :in => 5..30, :on => :create
  # validates_confirmation_of :password

  attr_accessor :password_confirmation

  before_create :hash_password

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def self.authenticate(username, password)
    user = User.find_by_username(username)

    if user && user.password == hash_plaintext_password(password)
      logger.info 'correct info'
      return user
    else
      return nil
     end
  end

  def is_referee?
    !self.referees.empty?
  end

  def is_referee_for?(tournament)
    tournament.referees.any? { |referee| referees.include?(referee) }
  end

  def is_current_referee_for?(player)
    @referees.map(&:tournament).select(&:is_running?).each do |tournament|
      return true if tournament.players.include? player
    end
  end

  def self.augment_if_exists(username) # if username exists, appends order number
    augmentation = 1
    new_user = username
    while User.exists?(:username => new_user)
      new_user = username + augmentation.to_s
      augmentation += 1
    end
    return new_user
  end

  def reset_password
    new_pass = SecureRandom.hex(6)
    self.password = User.hash_plaintext_password(new_pass)
    new_pass
  end

  private

  def hash_password
    return if self.password.blank?
    self.password = User.hash_plaintext_password(self.password)
  end

  def self.hash_plaintext_password(password)
    Digest::SHA1.hexdigest(password)
  end


end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController

  skip_before_filter :is_authenticated?, :only => [ :index, :new, :create ]
  before_filter :own_data?, :except => [ :index, :new, :create ]
  before_filter :is_admin?, :only => [:destroy]

  def index
    flash.keep(:notice)
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    calendar = Calendar.new
    @user.calendar = calendar
    if @user.save
      flash[:notice] = 'Käyttäjä luotiin onnistuneesti.'
      redirect_to root_path
    else
      render :action => "new"
    end
  end

  def update
    @user = User.find(params[:id])

    if params[:user] && params[:user].include?(:password) && params[:user].include?(:password_confirmation)
      params[:user][:password] = User.hash_plaintext_password(params[:user][:password])
      params[:user][:password_confirmation] = User.hash_plaintext_password(params[:user][:password_confirmation])
    end

    if @user.update_attributes(params[:user])
      flash[:notice] = 'Käyttäjätiedot päivitetty.'
      redirect_to(@user)
    else
      flash[:notice] = 'Päivitys ei onnistunut.'
      render :action => "edit"
    end
  end

  def reset_password
    @user = User.find(params[:id])
    new_pass = @user.reset_password
    msg = ManagementMailer.create_password_reset_message(@user, new_pass)
    begin
      ManagementMailer.deliver(msg)
      flash[:notice] = "Salasanan uudelleenasetus onnistui! Salasana on lähetetty pelaajalle sähköpostitse."
    rescue Net::SMTPAuthenticationError, Net::SMTPServerBusy, Net::SMTPSyntaxError, Net::SMTPFatalError, Net::SMTPUnknownError => e
      flash[:alert] = "Salasanaa ei voitu lähettää sähköpostitse. Pelaajan uusi salasana on #{new_pass}"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  # filter for preventing users from seeing others' data
  def own_data?
    unless params[:id] == session[:user_id].to_s || current_user.admin
      redirect_to root_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
%h1 Käyttäjätietojen muokkaus
%b= link_to "Vaihda kuvaa...", edit_user_picture_path(@user)
%table
  %tr
    %td
      %h3 Salasanan vaihto
      = form_for(@user) do |f|
        %p
          = f.label "Salasana"
          %br/
          = f.password_field :password
        %p
          = f.label "Salasana uudestaan"
          %br/
          = f.password_field :password_confirmation
        %p
          = f.submit "Päivitä"
      %h3 Pelaajatietojen muokkaus
      = form_for(@user) do |f|
        %p
          %b Pelaajatuomarit:
        %ul
          - @user.players.each do |player|
            - if player.referee != nil and player.tournament.is_running?
              %li
                %i>= player.alias
                \: #{player.referee.info} (#{player.referee.user.phone})
        %p
          = f.label "Etunimi"
          %br/
          = f.text_field :first_name
        %p
          = f.label "Sukunimi"
          %br/
          = f.text_field :last_name
        %p.secret
          = f.label :Puhelin
          %br/
          = f.text_field :phone
        %p.secret
          = f.label "Sähköposti"
          %br/
          = f.text_field :email
        %p
          = f.label "Osoite"
          %br/
          = f.text_field :address
        %p
          = f.label "Oppilaitos"
          %br/
          = f.text_field :university
        %p
          = f.label "Tiedekunta/vast"
          %br/
          = f.text_field :faculty
        %p
          = f.label "Ainelaitos"
          %br/
          = f.text_field :department
        %p
          = f.label "Silmät"
          %br/
          = f.text_field :eyes
        %p
          = f.label "Silmälasit"
          %br/
          = f.select( :glasses, [ "Aina", "Joskus", "Ei" ] )
        %p
          = f.label "Pituus"
          %br/
          = f.text_field :height, "size" => 3, "maxlength" => 3
          cm
        %p
          = f.label "Hiukset"
          %br/
          = f.text_field :hair
        %p
          = f.label "Muut tuntomerkit"
          %br/
          = f.text_field :other_notes
        %p
          = f.submit "Päivitä"
    %td
      - if @user.picture
        = image_tag(@user.picture.url)
      - else
        %b PELAAJALLA EI KUVAA TOISTAISEKSI

app/views/users/index.html.haml
%h3= t('open_registrations')
- Tournament.registration_open.each do |tournament|
  %ul
    - if tournament.special_event?
      %li= link_to tournament.title, new_special_tournament_ilmo_path(tournament)
    - else
      %li= link_to tournament.title, tournament_registration_path(tournament)

%h1 Login
= form_for(@user, url: session_url) do |f|
  = f.label :username, t('session.username')
  = f.text_field :username, size: 20
  %br/
  = f.label :password, t('session.password')
  = f.password_field :password, size: 20
  %br/
  = f.submit t('session.login')

app/views/users/new.html.haml
%h1 Uusi käyttäjä
%p
  %i (*pakollinen kenttä)
= form_for(@user, :html =>  {:class => 'validate'}) do |f|
  %p
    = f.label "Käyttäjätunnus*"
    %br/
    = f.text_field :username
  %p
    = f.label "Salasana*"
    %br/
    = f.password_field :password
  %p
    = f.label "Salasana uudestaan*"
    %br/
    = f.password_field :password_confirmation
  %p
    = f.label "Etunimi"
    %br/
    = f.text_field :first_name
  %p
    = f.label "Sukunimi"
    %br/
    = f.text_field :last_name
  %p.secret
    = f.label "Puhelin"
    %br/
    = f.text_field :phone
  %p.secret
    = f.label "Sähköposti"
    %br/
    = f.text_field :email
  %p
    = f.label "Osoite"
    %br/
    = f.text_field :address
  %p
    = f.label "Oppilaitos"
    %br/
    = f.text_field :university
  %p
    = f.label "Tiedekunta/vast"
    %br/
    = f.text_field :faculty
  %p
    = f.label "Ainelaitos"
    %br/
    = f.text_field :department
  %p
    = f.label "Silmät"
    %br/
    = f.text_field :eyes
  %p
    = f.label "Silmälasit"
    %br/
    = f.select(:glasses, ["Aina", "Joskus", "Ei"])
  %p
    = f.label "Pituus"
    %br/
    = f.text_field :height, "size" => 3, "maxlength" => 3
    cm
  %p
    = f.label "Hiukset"
    %br/
    = f.text_field :hair
  %p
    = f.label "Muut tuntomerkit"
    %br/
    = f.text_field :other_notes
  %p
    = f.submit "Create"

app/views/users/show.html.haml
%table
  %tr
    %td
      %p
        %b Käyttäjä:
        = h @user.username
      %p
        %b Nimi:
        = h @user.full_name
      %p
        %b Oppilaitos:
        = h @user.university
        \/ #{h @user.faculty} /  #{h @user.department}
      %p
        %b Puhelin:
        = h @user.phone
      %p
        %b Sähköposti:
        = h @user.email
      %p
        %b Osoite:
        = h @user.address
      %p
        %b Silmät:
        = h @user.eyes
      %p
        %b Lasit:
        = h @user.glasses
      %p
        %b Pituus:
        = h @user.height
      %p
        %b Hiukset:
        = h @user.hair
      %p
        %b Muut tuntomerkit:
        = h @user.other_notes
      %p
        %b Pelaajatuomarit:
      %ul
        - @user.players.each do |player|
          - if player.referee != nil and player.tournament.is_running?
            %li
              %i>= player.alias
              \: #{player.referee.info} (#{player.referee.user.phone})
    %td
      - if @user.picture
        = image_tag(@user.picture.url)
      - else
        %b PELAAJALLA EI KUVAA TOISTAISEKSI

app/views/users/tempindex.html.haml
%h1 Listing users
%table
  %tr
    %th Username
    %th Phone
    %th Address
    %th Eyes
    %th Glasses
    %th Height
    %th Hair
    %th Other notes
  - for user in @users
    %tr
      %td= h user.username
      %td= h user.phone
      %td= h user.address
      %td= h user.eyes
      %td= h user.glasses
      %td= h user.height
      %td= h user.hair
      %td= h user.other_notes
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New user', new_user_path