config/routes.rb
HYSMurhamaster::Application.routes.draw do

  root to: 'tournaments#index'

  resources :teams do
    resources :players
  end

  resources :calendars

  resources :tournaments do
    resources :ilmos
    resources :players
    resources :referees
    resources :teams, controller: 'tournaments/teams'
    resources :team_assignments
    resources :targets
    resources :rings do
      resources :assignments
    end
    resources :warrants
    resources :events
  end

  resources :special_tournaments do
    resources :ilmos, controller: 'special_tournaments/ilmos'
    resources :targets, controller: 'special_tournaments/targets'
    resources :players, controller: 'special_tournaments/players'
  end

  resources :referees do
    resources :players
  end

  resources :users do
    resources :targets
    resource :calendar
    resource :picture
  end

  get '/tournaments/:tournament_id/registration', to: 'ilmos#new', as: :tournament_registration
  match '/tournaments/:tournament_id/targets/:id/print' => 'targets#print'
  match '/tournaments/:tournament_id/resend_registration_mails' => 'ilmos#resend_registration_mails'
  match '/users/:id/reset_password' => 'users#reset_password'
  # match '/images/*file_name' => 'pictures#display'
  match 'pictures/:id/:style.:format', controller: 'pictures', action: 'display', conditions: { method: :get }
  resource :session
  match '/login' => 'users#index', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  # FIXME dirty hack for ropecon
  match '/ropecon', controller: 'special_tournaments/targets', action: 'index', defaults: {special_tournament_id: Tournament.all.select(&:special_event?).last.id }
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :tournament
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :is_referee?, :except => :index
  skip_before_filter :is_authenticated?, :only => :index
  
  layout "events", :except => [:new, :edit]
  
  def index 
    @tournament = Tournament.find(params[:tournament_id])
    @events = @tournament.events.sort_by {|e| e.time}    
    if not logged_in?
      @is_referee = false
    else
      @is_referee = current_user.is_referee_for?(@tournament)
    end
  end

  def show
    @tournament = Tournament.find(params[:tournament_id])
    
    @event = Event.find(params[:id])
  end

  def new
    @tournament = Tournament.find(params[:tournament_id])
    @event = Event.new
    render :layout => "application"
  end

  def edit
    @tournament = Tournament.find(params[:tournament_id])
    @event = Event.find(params[:id])
    render :layout => "application"
  end

  def create
    @tournament = Tournament.find(params[:tournament_id])
    @event = Event.new(params[:event])
    @event.tournament = @tournament
    @event.save
    Tournament.update_stats(@tournament)    
    redirect_to tournament_events_path(@tournament)
  end

  def update
    @tournament = Tournament.find(params[:tournament_id])
    @event = Event.find(params[:id])
    @event.update_attributes(params[:event])
    Tournament.update_stats(@tournament)    
    flash[:notice] = 'Event was successfully updated.'
    redirect_to tournament_events_path(@tournament)
  end


  def destroy
    @tournament = Tournament.find(params[:tournament_id])
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to tournament_events_path(@tournament)
  end
end

app/helpers/events_helper.rb
#encoding: utf-8
module EventsHelper
  
  def formatted_duration(tournament)
    return "#{tournament.start_date.day}.#{tournament.start_date.month}.-#{tournament.finish_date.day}.#{tournament.finish_date.month}."
  end
  
  def formatted_duration_with_year(tournament)
    return "#{formatted_duration(tournament)}#{tournament.finish_date.year}"
  end
  
  def tournament_status(tournament)
    if tournament.is_running?
      return "Peli käynnissä"
    elsif DateTime.now < tournament.app_deadline
      return "Ilmoittautuminen käynnissä"
    elsif DateTime.now > tournament.app_deadline and Date.today < tournament.start_date
      return "Ilmoittautuminen on päättynyt"
    else
      return "Peli on päättynyt"
    end
  end
    
end

app/views/events/edit.html.haml
%h1 Uusi tapahtuma
= form_for([@tournament, @event]) do |eventf|
  %p
    = eventf.label "Otsikko"
    %br/
    = eventf.text_field :title
  %p
    = eventf.label "Ajankohta"
    %br/
    = eventf.datetime_select :time
  = eventf.label "Sisältö"
  %i (Ymmärtää yleisimmät HTML:n tekstimuotoilutagit)
  %br/
  = eventf.text_area :content, :cols => 80
  %table
    %tr
      %td
        = eventf.label "Murhia"
      %td
        = eventf.select :murders, (0..10).to_a
      %td
        = eventf.label "Tappoja"
      %td
        = eventf.select :kills, (0..10).to_a
      %td
        = eventf.label "Pidätyksiä"
      %td
        = eventf.select :arrests, (0..10).to_a
    %tr
      %td
        = eventf.label "Sivullisia"
      %td
        = eventf.select :collaterals, (0..40).to_a
      %td
        = eventf.label "Todistajia"
      %td
        = eventf.select :witnesses, (0..40).to_a
      %td
        = eventf.label "Silminnäkijöitä"
      %td
        = eventf.select :eyewitnesses, (0..40).to_a
  = eventf.submit "Lähetä"

app/views/events/index.html.haml
%hr

- @events.reverse.each do |event|
  %h3{class: event}= "#{finnish_date(event.time)} #{event.title}"
  - if @is_referee
    = link_to('Muokkaa tapahtumaa', edit_tournament_event_path(@tournament, event))
  %p{class: event}
    != simple_format(event.content, {class: event}, {sanitize: false})
  %hr

app/views/events/new.html.haml
%h3 Uusi tapahtuma
= form_for([@tournament, @event]) do |eventf|
  %p
    = eventf.label "Otsikko"
    %br/
    = eventf.text_field :title
  %p
    = eventf.label "Ajankohta"
    %br/
    = eventf.datetime_select :time
  = eventf.label "Sisältö"
  %i (Ymmärtää yleisimmät HTML:n tekstimuotoilutagit)
  %br/
  = eventf.text_area :content, :cols => 80
  %table
    %tr
      %td
        = eventf.label "Murhia"
      %td
        = eventf.select :murders, (0..10).to_a
      %td
        = eventf.label "Tappoja"
      %td
        = eventf.select :kills, (0..10).to_a
      %td
        = eventf.label "Pidätyksiä"
      %td
        = eventf.select :arrests, (0..10).to_a
    %tr
      %td
        = eventf.label "Sivullisia"
      %td
        = eventf.select :collaterals, (0..40).to_a
      %td
        = eventf.label "Todistajia"
      %td
        = eventf.select :murders, (0..40).to_a
      %td
        = eventf.label "Silminnäkijöitä"
      %td
        = eventf.select :eyewitnesses, (0..40).to_a
  = eventf.submit "Lähetä"

app/views/events/show.html.haml
%h3.event_header
  = finnish_date(@event.time)
  = @event.title
%p
  = simple_format(@event.content, {}, {:sanitize => false})
= @event.tournament.title
= @event.tournament.events.first.title
%hr/