config/routes.rb
HYSMurhamaster::Application.routes.draw do

  root to: 'tournaments#index'

  resources :teams do
    resources :players
  end

  resources :calendars

  resources :tournaments do
    resources :ilmos
    resources :players
    resources :referees
    resources :teams, controller: 'tournaments/teams'
    resources :team_assignments
    resources :targets
    resources :rings do
      resources :assignments
    end
    resources :warrants
    resources :events
  end

  resources :special_tournaments do
    resources :ilmos, controller: 'special_tournaments/ilmos'
    resources :targets, controller: 'special_tournaments/targets'
    resources :players, controller: 'special_tournaments/players'
  end

  resources :referees do
    resources :players
  end

  resources :users do
    resources :targets
    resource :calendar
    resource :picture
  end

  get '/tournaments/:tournament_id/registration', to: 'ilmos#new', as: :tournament_registration
  match '/tournaments/:tournament_id/targets/:id/print' => 'targets#print'
  match '/tournaments/:tournament_id/resend_registration_mails' => 'ilmos#resend_registration_mails'
  match '/users/:id/reset_password' => 'users#reset_password'
  # match '/images/*file_name' => 'pictures#display'
  match 'pictures/:id/:style.:format', controller: 'pictures', action: 'display', conditions: { method: :get }
  resource :session
  match '/login' => 'users#index', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  # FIXME dirty hack for ropecon
  match '/ropecon', controller: 'special_tournaments/targets', action: 'index', defaults: {special_tournament_id: Tournament.all.select(&:special_event?).last.id }
end

app/models/player.rb
class Player < ActiveRecord::Base

  belongs_to :user
  belongs_to :tournament
  belongs_to :team
  belongs_to :referee

  has_one :warrant
  has_many :assignments
  has_many :targets, :through => :assignments

  validates_inclusion_of :status, :in => [:waiting_approval, :active, :detective, :dead]

  scope :waiting_players, :conditions => ["status = ?", "waiting_approval"]

  scope :active_players, :conditions => ["status = ?", "active"]
  scope :dead_players, :conditions => ["status = ?", "dead"]
  scope :detectives, :conditions => ["status = ?", "detective"]

  scope :participating, :conditions => ["status != ?", "waiting_approval"]

  before_validation :default_status
  before_validation :symbolize_status

  def status
    status = read_attribute(:status)
    status.to_sym if status
  end
  def status=(value)
    write_attribute(:status, value)
  end

  def waiting_approval?
    self.status == :waiting_approval
  end

  def detective?
    self.status == :detective
  end

  def active?
    self.status == :active
  end

  def dead?
    self.status == :dead
  end


  def with_real_name
    "#{self.user.full_name}, #{self.alias}"
  end

  def real_name
    self.user.full_name
  end

  def to_s
    if team != nil
      "%s (%s)" % [ self.alias, self.team.name ]
    else
      self.alias
    end
  end

  private

  def symbolize_status
    self.status = self.status.to_sym if self.status
  end

  def default_status
    self.status ||= :waiting_approval
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_filter :own_data?, :except => [:show, :index, :update, :destroy, :edit]
  before_filter :is_referee?, :only => [:index, :show, :update, :destroy, :edit]


  def index
    @tournament = Tournament.find(params[:tournament_id])
    @active_players = @tournament.players.active_players
    @detectives = @tournament.players.detectives
    @dead_players = @tournament.players.dead_players
  end

  def show
    @player = Player.find(params[:id])
    @user = @player.user
  end

  def new
  end

  def edit
    @player = Player.find(params[:id])
    @tournament = Tournament.find(params[:tournament_id])
  end

  def create
  end

  def update
    player = Player.find(params[:id])
    was_active = player.active?
    old_alias = player.alias
    # log killings
    if params[:player]
      params[:player][:status] = params[:player][:status].to_sym if params[:player].include?(:status)
      player.update_attributes(params[:player])
      # if player was active, take care of rings and tournament stats
      kill(player) if params[:player][:status] == :dead && was_active
      # alias is only modifiable from ilmo listing
      if params[:player][:alias] != old_alias
        redirect_to tournament_ilmos_path(player.tournament)
      else
        redirect_to tournament_players_path(player.tournament)
      end
    else
      redirect_to tournament_players_path(player.tournament)
    end
  end

  def destroy
    player = Player.find(params[:id])
    tournament = player.tournament
    player.destroy
    redirect_to tournament_players_path(tournament)
  end

  private

  def kill(player)
    logger.info "Killing player"
    # moving player's targets to new hunters
    RingsController.drop_from_rings(player)
    WarrantsController.drop_from_warrants(player)
  end

end

app/controllers/special_tournaments/players_controller.rb
class SpecialTournaments::PlayersController < ApplicationController
  before_filter :is_referee?, :only => [:index, :show, :update, :destroy, :edit]


  def index
    @tournament = Tournament.find(params[:special_tournament_id])
  end

  def show
    @player = Player.find_by_tournament_id_and_id(params[:special_tournament_id], params[:id])
  end

  def edit
    @player = Player.find(params[:id])
    @tournament = Tournament.find(params[:tournament_id])
  end

  def update
    player = Player.find(params[:id])
    old_alias = player.alias
    # log killings
    if params[:player]
      params[:player][:status] = params[:player][:status].to_sym if params[:player].include?(:status)
      player.update_attributes(params[:player])
      # alias is only modifiable from ilmo listing
      if params[:player][:alias] != old_alias
        redirect_to special_tournament_ilmos_path(player.tournament)
      else
        redirect_to special_tournament_players_path(player.tournament)
      end
    else
      redirect_to special_tournament_players_path(player.tournament)
    end
  end

  def destroy
    player = Player.find(params[:id])
    tournament = player.tournament
    player.destroy
    redirect_to special_tournament_players_path(tournament)
  end

  def is_referee?
    tournament = Tournament.find(params[:special_tournament_id])
    if current_user.is_referee_for?(tournament) && tournament.is_relevant_for_referee?
      logger.info("user #{current_user.username} accessed a referee-restricted page")
      true
    else
      logger.info("user #{current_user.username} tried to access referee-restricted page without permission")
      redirect_to(root_path)
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/edit.html.haml
= form_for( [@tournament, @player] ) do |f|
  %b= @player.with_real_name
  %p
    = f.label :Peitenimi
    %br/
    = f.text_field :alias
  - if not @player.waiting_approval?
    %p
      = f.label :Tuomari
      %br/
      = collection_select :player, :referee_id, @tournament.referees, :id, :full_info
  %p
    = f.submit "Päivitä"

app/views/players/index.html.haml
%h1 Listing players
%h2 Elossaolevat
%table
  %tr
    %th Käyttäjä
    %th Alias
    %th Kohdesivu
    %th Pelaajatuomari
  - if @tournament.team_game?
    - @tournament.teams.each do |team|
      - if team.players.any? {|p| p.active?}
        %tr
          %td
            %b= h team.name
          %td
          %td
          %td
      - (team.players.select {|p| p.active?}).each do |player|
        %tr
          %td= h player.user.full_name
          %td= h player.alias
          %td= link_to player.real_name, tournament_player_path(@tournament, player)
          %td
            - if player.referee != nil
              = h player.referee.user.full_name
            - else
              = link_to 'Lisää tuomari', edit_tournament_player_path(@tournament, player)
          %td
            = form_for [@tournament, player] do |p|
              = p.hidden_field :status, { :value => :dead }
              = submit_tag "Kuolleeksi", :onclick => 'return #{confirm_javascript_function("Siirretäänkö pelaaja kuolleeksi?")}'
  - else
    - for player in @active_players
      %tr
        %td= h player.user.full_name
        %td= h player.alias
        %td= link_to player.real_name, tournament_player_path(@tournament, player)
        %td
          - if player.referee != nil
            = h player.referee.user.full_name
          - else
            = link_to 'Lisää tuomari', edit_tournament_player_path(@tournament, player)
        %td
          = form_for [@tournament, player] do |p|
            = p.hidden_field :status, { :value => :dead }
            = submit_tag "Kuolleeksi", :onclick => 'return #{confirm_javascript_function("Siirretäänkö pelaaja kuolleeksi?")}'
%h2 Etsivät
%table
  %tr
    %th Käyttäjä
    %th Alias
    %th Kohdesivu
    %th Pelaajatuomari
  - for player in @detectives
    %tr
      %td= h player.user.full_name
      %td= h player.alias
      %td= link_to player.real_name, tournament_player_path(@tournament, player)
      %td
        - if player.referee != nil
          = h player.referee.user.full_name
        - else
          = link_to 'Lisää tuomari', edit_tournament_player_path(@tournament, player)
      %td
        = form_for [@tournament, player] do |p|
          = p.hidden_field :status, { :value => :dead }
          = submit_tag "Kuolleeksi", :onclick => 'return #{confirm_javascript_function("Siirretäänkö pelaaja kuolleeksi?")}'
%h2 Kuolleet
%table
  %tr
    %th Käyttäjä
    %th Alias
    %th Kohdesivu
    %th Pelaajatuomari
  - for player in @dead_players
    %tr
      %td= h player.user.full_name
      %td= h player.alias
      %td= link_to player.real_name, tournament_player_path(@tournament, player)
      %td
        - if player.referee != nil
          = h player.referee.user.full_name
        - else
          = link_to 'Lisää tuomari', edit_tournament_player_path(@tournament, player)
      %td
        = form_for [@tournament, player] do |p|
          = p.hidden_field :status, { :value => :detective }
          = submit_tag "Etsiväksi"
      %td
        = form_for [@tournament, player] do |p|
          = p.hidden_field :status, { :value => :active }
          = submit_tag "Henkiin"
%br/

app/views/players/show.html.haml
%h2= @player.tournament.title
- if @player.user.picture
  = image_tag(@player.user.picture.url)
- else
  %b PELAAJALLA EI KUVAA TOISTAISEKSI
%table.top_align{:cellspacing => "20"}
  %tr
    %th
      %h3 Perustiedot
      %h3
    %th
      %h3 Kalenteri
      %h3
  %tr
    %td
      %p
        - if current_user.is_referee_for?(@player.tournament)
          %i Kirjautunut viimeksi: #{nil_date_handler(@user.last_login)}
      %p
        %b Nimi:
        = h "%s %s" % [ @user.first_name, @user.last_name ]
      %p
        %b Peitenimi:
        = h @player.alias
      - if @player.team != nil
        %p
          %b Joukkue:
          = h @player.team.name
      %p
        %b Puhelin:
        = h @user.phone
      %p
        %b Sähköposti:
        = h @user.email
      %p
        %b Osoite:
        = h @user.address
      %p
        %b Oppilaitos:
        = h @user.university
        \/ #{h @user.faculty} /  #{h @user.department}
      %p
        %b Silmät:
        = h @user.eyes
      %p
        %b Silmälasit:
        = h @user.glasses
      %p
        %b Pituus:
        = h @user.height
      %p
        %b Hiukset:
        = h @user.hair
      %p
        %b Muut tuntomerkit:
        = h @user.other_notes
      %p
        - if @player.referee != nil
          %b Tuomari:
          = h @player.referee.user.full_name
          , #{h @player.referee.user.phone}
        - else
          %b EI PELAAJATUOMARIA
    %td
      %p
        %b Maanantai:
        = simple_format(@user.calendar.monday)
      %p
        %b Tiistai:
        = simple_format(@user.calendar.tuesday)
      %p
        %b Keskiviikko:
        = simple_format(@user.calendar.wednesday)
      %p
        %b Torstai:
        = simple_format(@user.calendar.thursday)
      %p
        %b Perjantai:
        = simple_format(@user.calendar.friday)
      %p
        %b Lauantai:
        = simple_format(@user.calendar.saturday)
      %p
        %b Sunnuntai:
        = simple_format(@user.calendar.sunday)
      %p
        %b Liikennevälineet, muut huomiot:
        = simple_format(@user.calendar.misc)
= link_to 'Takaisin', :back